version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blester_dev
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - blester_net

  node:
    image: node:20
    working_dir: /app/assets
    volumes:
      - ./assets:/app/assets
    command: sh -c "npm install && npm run deploy -- --watch"
    networks:
      - blester_net

  web:
    image: elixir:1.16
    working_dir: /app
    command: sh -c "mix deps.get && mix ecto.setup && mix phx.server"
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@db:5432/blester_dev
      SECRET_KEY_BASE: insecuredockersecretkeybase
    ports:
      - '4000:4000'
    depends_on:
      - db
      - node
    volumes:
      - ./:/app
    networks:
      - blester_net

volumes:
  db_data:

networks:
  blester_net: 