defmodule Blester.Repo.Migrations.AddCategoriesTableAndCategoryIdToProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
    end
    create unique_index(:categories, [:name], name: "categories_unique_name_index")

    alter table(:products) do
      add :category_id, references(:categories, type: :uuid, on_delete: :nilify_all)
      remove :category
    end
  end

  def down do
    alter table(:products) do
      add :category, :text
      remove :category_id
    end
    drop_if_exists unique_index(:categories, [:name], name: "categories_unique_name_index")
    drop table(:categories)
  end
end
